name: Deploy

on:
  release:
    types: [released]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: | 
            6.x
            7.x
            8.x
      - name: prepare version
        run: |
          echo "$VERSION"
      - name: pack LeviySoft.Visor
        run: |
          cd src
          dotnet pack LeviySoft.Visor/LeviySoft.Visor.csproj -c Release /p:Version=${{env.VERSION}} /p:PackageVersion=${{env.VERSION}}
      - name: pack LeviySoft.Visor.Gen
        run: |
          cd src
          dotnet pack LeviySoft.Visor.Gen/LeviySoft.Visor.Gen.csproj -c Release /p:Version=${{env.VERSION}} /p:PackageVersion=${{env.VERSION}}
      - name: pack LeviySoft.Visor.LanguageExt
        run: |
          cd src
          dotnet pack LeviySoft.Visor.LanguageExt/LeviySoft.Visor.LanguageExt.csproj -c Release /p:Version=${{env.VERSION}} /p:PackageVersion=${{env.VERSION}}
      - name: publish
        run: |
          cd src
          dotnet nuget push **/LeviySoft.Visor.*.nupkg -k ${{secrets.NUGET_APIKEY}} -s https://www.nuget.org